name: Call AWS Lambda and Comment S3 Link

on:
  push:
    branches:
      - main  # Adjust to your branch name
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  call-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Adjust to your region

      - name: Set and Debug Environment Variables
        run: |
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_SERVER_URL: ${GITHUB_SERVER_URL}"
          REPO_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
          echo "Repository URL: $REPO_URL"
          echo "REPO_URL=$REPO_URL" >> $GITHUB_ENV
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Invoke Lambda function
        id: invoke_lambda
        env:
          REPO_URL: ${{ env.REPO_URL }}
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
        run: |
          echo "Using Repository URL: $REPO_URL"
          echo "Using Branch Name: $BRANCH_NAME"
          PAYLOAD=$(jq -n --arg branch "$BRANCH_NAME" --arg url "$REPO_URL" '{type: "github", branch: $branch, url: $url}')
          echo "Payload: $PAYLOAD"
          aws lambda invoke --function-name Core-Engine-Docker --payload "$PAYLOAD" response.json --cli-binary-format raw-in-base64-out
          cat response.json
          S3_LINK=$(cat response.json | jq -r '.body')
          echo "S3_LINK=$S3_LINK" >> $GITHUB_ENV

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const s3Link = process.env.S3_LINK;
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Here is the S3 link: ${s3Link}`
            });
